parameters: {}
environment: {}
packages:
  - name: upload
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: dumps
        binary: false
        main: "Main"
        runtime: go:1.20
        web: false
        webSecure: false
        parameters: {}
        environment:
          {
            accessKeyID: "${ACCESS_KEY_ID}",
            secretAccessKey: "${SECRET_ACCESS_KEY}",
          }
        annotations: {}
        limits: { timeout: 300000 }
        triggers:
          - name: daily
            sourceType: scheduler
            sourceDetails:
              cron: 0 8 * * *
      - name: foundings
        binary: false
        main: "Main"
        runtime: go:1.20
        web: false
        webSecure: false
        parameters: {}
        environment:
          {
            accessKeyID: "${ACCESS_KEY_ID}",
            secretAccessKey: "${SECRET_ACCESS_KEY}",
          }
        annotations: {}
        limits: { timeout: 300000 }
        triggers:
          - name: daily
            sourceType: scheduler
            sourceDetails:
              cron: 0 6 * * *
