name: DigitalOcean Function Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with: 
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Connect to serverless namespace
      run: doctl serverless connect nsarchive-upload
    - name: Deploy function
      run: doctl serverless deploy .
